.\" -*- nroff -*-
.TH YPHELPER 8 "August 2001" "YP Server" "Reference Manual"
.SH NAME
yphelper \- helper application for internal use
.SH DESCRIPTION
.B yphelper
is a internal helper application for ypserv and should not be
used by the normal user or system administrator.
.SH AUTHOR
.B yphelper
was written by Thorsten Kukuk <kukuk@suse.de>.
