name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: ["3.10", "3.11", "3.12"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Work around arm64 support on MacOS
        # https://github.com/actions/virtual-environments/issues/2557
        if: matrix.os == 'macos-latest'
        run: sudo rm -Rf /Library/Developer/CommandLineTools/SDKs/*

      - name: Install dependencies
        run: python -m pip install --upgrade pip

      - name: Build
        run: pip -v install -e .

      - name: install test dependencies
        run: |
          python3 -m pip install pytest pytest-asyncio pytest-forked hypothesis pytest-mock
          python3 -m pip install -r test/requirements.txt
          python3 -m pip install .

      - name: run tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python3 -m pytest --forked
